Importo las librerías para trabajar ETL y EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import re
import math
sns.set_style('whitegrid')
sns.set_palette('tab10')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode,iplot
import datetime as dato
plt.style.use('seaborn-notebook')
import warnings
warnings.filterwarnings('ignore')
from ydata_profiling import ProfileReport

Ingesta de archivos csv

In [2]:
dfml=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/ML_ETL_plataformas.csv')

In [4]:
dfmlr1=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/1.csv')
dfmlr2=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/2.csv')
dfmlr3=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/3.csv')
dfmlr4=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/4.csv')
dfmlr5=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/5.csv')
dfmlr6=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/6.csv')
dfmlr7=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/7.csv')
dfmlr8=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/8.csv')

In [5]:
dfmlr=(pd.concat([dfmlr1,dfmlr2,dfmlr3,dfmlr4,dfmlr5,dfmlr6,dfmlr7,dfmlr8], axis=0))

In [12]:
dfml.shape

(22998, 17)

In [6]:
dfmlr.shape

(11024289, 4)

Arranco el proceso de EDA (Exploraty Data Anaysis)

In [8]:
dfml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             22998 non-null  object
 1   show_id        22998 non-null  object
 2   type           22998 non-null  object
 3   title          22998 non-null  object
 4   director       22998 non-null  object
 5   cast           22998 non-null  object
 6   country        22998 non-null  object
 7   date_added     22998 non-null  object
 8   release_year   22998 non-null  int64
 9   rating         22998 non-null  object
 10  duration       22998 non-null  object
 11  listed_in      22998 non-null  object
 12  description    22998 non-null  object
 13  plataforma     22998 non-null  object
 14  duration_int   22998 non-null  int64
 15  duration_type  22998 non-null  object
 16  score          19488 non-null  float64
dtypes: float64(1), int64(2), object(14)
memory usage: 3.0+ MB

In [14]:
dfml.sample(2)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma,duration_int,duration_type,score
20969,ns6779,s6779,movie,for greater glory,dean wright,"rubén blades, bruce greenwood, bruce mcgill, p...",mexico,2019-08-02 00:00:00,2012,R,145 min,"dramas, international movies",when a vicious war against catholics is waged ...,netflix,145,min,3.458418
19367,ns5177,s5177,movie,mea culpa,"raúl campos, jan suter",alexis de anda,mexico,2017-11-10 00:00:00,2017,TV-MA,54 min,stand-up comedy,"raw and outspoken, comedian alexis de anda bar...",netflix,54,min,3.541068

In [13]:
dfmlr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11024289 entries, 0 to 1499999
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   rating     float64
 2   timestamp  int64
 3   movieId    object
dtypes: float64(1), int64(2), object(1)
memory usage: 420.5+ MB

In [15]:
dfmlr.sample(2)

         userId  rating   timestamp movieId
1460536   30862     4.0  1290841447   as933
821690    54911     3.0  1043042230  ns5652

Busco y sumo valores nulos

In [16]:
dfml.isna().sum()

id                  0
show_id             0
type                0
title               0
director            0
cast                0
country             0
date_added          0
release_year        0
rating              0
duration            0
listed_in           0
description         0
plataforma          0
duration_int        0
duration_type       0
score            3510
dtype: int64

In [17]:
dfmlr.isna().sum()

userId       0
rating       0
timestamp    0
movieId      0
dtype: int64

Elimino colmnas innecesarias : 'show_id', 'description', 'sin dato'

Renombro la columna genero

In [24]:
dfml = dfml.rename(columns={'listed_in':'genre'})
dfml.head()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genre,description,plataforma,duration_int,duration_type,score
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30 00:00:00,2014,G,113 min,"comedy, drama",a small fishing village must procure a local d...,amazon,113,min,3.549127
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30 00:00:00,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,amazon,110,min,3.556886
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30 00:00:00,2017,G,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,amazon,74,min,3.604124
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30 00:00:00,2014,G,69 min,documentary,"pink breaks the mold once again, bringing her ...",amazon,69,min,3.547085
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30 00:00:00,1989,G,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,amazon,45,min,3.532158

In [25]:
dfml['genre'] = dfml['genre'].apply(lambda x: x.split(",")(0))

TypeError: 'list' object is not callable

Uno los archivos desde la columna 'movieid'

In [13]:
dfcompl = dfml.merge(dfmlr, left_on='id', right_on='movieId', how='outer')

In [14]:
dfcompl.shape

(11024289, 21)

In [15]:
dfcompl.sample(10)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating_x,...,listed_in,description,plataforma,duration_int,duration_type,score,userId,rating_y,timestamp,movieId
1938229,as4042,s4042,movie,woman in the woods,kevin ang,"brian sy, mercedes cabral, lotlot bustamante, ...",Sin dato,Sin dato,2021,G,...,"action, science fiction","when jason's father dies, he goes on an advent...",amazon,88,min,3.463617,20899,2.0,1147688040,as4042
5796093,hs980,s980,tv show,line of duty,Sin dato,Sin dato,united kingdom,2021-02-12 00:00:00,2012,TV-MA,...,"crime, drama, international",set in the fictional police anti-corruption un...,hulu,5,Seasons,3.556723,65743,4.0,1202224941,hs980
5162076,ds1107,s1107,movie,now you see it,duwayne dunham,"alyson michalka, johnny pacar, frank langella,...",united states,2019-11-12 00:00:00,2005,TV-G,...,"coming of age, fantasy",an aspiring tv producer searches for the world...,disney,89,min,3.555118,249225,3.0,1429465937,ds1107
8167438,ns2854,s2854,movie,fat ballerina - david a. arnold,milton horowitz,david a. arnold,united states,2020-03-02 00:00:00,2020,TV-MA,...,stand-up comedy,"finally comfortable in his skin, seasoned comi...",netflix,61,min,3.427350,5942,5.0,851262103,ns2854
9577706,ns5792,s5792,movie,"tomasz jachimek, jacek stramik laugh at live",Sin dato,"tomasz jachimek, jacek stramik",Sin dato,2016-09-19 00:00:00,2016,TV-MA,...,stand-up comedy,"writer, actor and satirist tomasz jachimek tea...",netflix,63,min,3.512371,77309,3.5,1133212803,ns5792
9255324,ns5121,s5121,tv show,cheuk wan-chi: two night stand,Sin dato,cheuk wan chi,Sin dato,2017-12-15 00:00:00,2015,TV-MA,...,"international tv shows, stand-up comedy & talk...",writer and stand-up comedian cheuk wan-chi cra...,netflix,1,Season,3.515730,256341,4.0,1191346691,ns5121
3913456,as8166,s8166,movie,a different kind of christmas,tom mcloughlin,"shelley long, barry bostwick, bruce kirby, nat...",Sin dato,Sin dato,1996,13+,...,drama,what is like to grow up with a dad who truly b...,amazon,92,min,3.481781,53696,3.0,840747306,as8166
5613690,hs600,s600,tv show,jóvenes y rebeldes,Sin dato,Sin dato,Sin dato,2021-06-17 00:00:00,1999,G,...,"comedy, latino",esta comedia dramática nostálgica producida po...,hulu,1,Season,3.495475,26576,3.0,1111527034,hs600
5618513,hs610,s610,movie,gone girl,Sin dato,Sin dato,united states,2021-06-15 00:00:00,2014,TV-MA,...,"crime, drama, mystery",on the occasion of his fifth wedding anniversa...,hulu,146,min,3.537267,14046,5.0,1014314659,hs610
9575593,ns5788,s5788,movie,"katarzyna piasecka, rafał pacześ seriously funny",Sin dato,"katarzyna piasecka, rafał pacześ",Sin dato,2016-09-19 00:00:00,2016,TV-MA,...,stand-up comedy,polish comedians rafał pacześ and katarzyna pi...,netflix,65,min,3.588694,38312,4.0,1478892765,ns5788

Se analiza a un usuario X en particular

In [16]:
dato = dfcompl.loc[dfcompl['userId']==543]
dato.shape
dato.head(5)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating_x,...,listed_in,description,plataforma,duration_int,duration_type,score,userId,rating_y,timestamp,movieId
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30 00:00:00,2014,G,...,"comedy, drama",a small fishing village must procure a local d...,amazon,113,min,3.549127,543,5.0,1059596582,as1
5364,as12,s12,movie,take care,liz tuccillo,"leslie bibb, kevin curtis, nadia dajani",united states,2021-04-10 00:00:00,2014,G,...,comedy,"when a car crash leaves frannie immobilized, s...",amazon,93,min,3.579348,543,3.0,962139925,as12
7739,as17,s17,movie,zoombies,glenn miller,"marcus anderson, kaiwi lyman, andrew asper",Sin dato,Sin dato,2016,13+,...,"horror, science fiction",when a strange virus quickly spreads through a...,amazon,87,min,3.524655,543,3.0,963806452,as17
14391,as31,s31,tv show,yu-gi-oh! 5d's,Sin dato,"gregory abbey, bella hudson, ed paul",Sin dato,Sin dato,2011,TV-Y7,...,"anime, kids",with the defeat of director goodwin and the da...,amazon,2,Seasons,3.522857,543,5.0,943800914,as31
71924,as151,s151,movie,wash your hands & more classic kids songs - ki...,moonbug entertainment,Sin dato,Sin dato,Sin dato,2020,ALL,...,kids,a new collection of colorful and wonderfully e...,amazon,30,min,3.577621,543,1.0,963807270,as151

Elimino las columnas que no seran necesarias para la aplicacion del modelo

In [17]:
dfcompl = dfcompl.drop(columns='Sin dato')

KeyError: "['Sin dato'] not found in axis"