Importo las librerías para trabajar

In [1]:
import pandas as pd
import requests
import shutil
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import LabelEncoder
from scipy import sparse
from surprise import Dataset, Reader
from surprise import SVD
from surprise import accuracy
from surprise.model_selection import train_test_split
import gradio as gr

In [2]:
dfml=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/ML_ETL_plataformas.csv')

In [3]:
dfmlr1=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/1.csv')
dfmlr2=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/2.csv')
dfmlr3=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/3.csv')
dfmlr4=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/4.csv')
dfmlr5=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/5.csv')
dfmlr6=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/6.csv')
dfmlr7=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/7.csv')
dfmlr8=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/8.csv')

In [4]:
dfmlr=(pd.concat([dfmlr1,dfmlr2,dfmlr3,dfmlr4,dfmlr5,dfmlr6,dfmlr7,dfmlr8], axis=0))

Elimino la columna 'timespan' de df_users porque no la vamos a utilizar

In [5]:
dfmlr = dfmlr.drop(['timestamp'], axis=1)

In [6]:
dfml.head(1)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma,duration_int,duration_type,score
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30 00:00:00,2014,G,113 min,"comedy, drama",a small fishing village must procure a local d...,amazon,113,min,3.549127

Elimino columna no relevantes para el análisis

In [7]:
dfml= dfml.drop(['show_id','director','cast','country','date_added','release_year','rating','duration','description','duration_int','duration_type','score'], axis=1)

In [8]:
dfml.head(1)

    id   type                title      listed_in plataforma
0  as1  movie  the grand seduction  comedy, drama     amazon

Cambio de nombre de la columna 'id' a 'movieId'

In [9]:
dfml = dfml.rename(columns={'id': 'movieId'})
# We have now the same colum 'movieId' for both dfs

In [10]:
dfml.head(2)

  movieId   type                 title             listed_in plataforma
0     as1  movie   the grand seduction         comedy, drama     amazon
1     as2  movie  take care good night  drama, international     amazon

Uno los dos df

In [21]:
dfcompl = pd.merge(left=dfmlr,right=dfml)

In [11]:
dfcompl.shape
# we have 11024289 rows

NameError: name 'dfcompl' is not defined

In [26]:
dfcompl.head(5)

,userId,rating,movieId,type,title,listed_in,plataforma
0,1,1.0,as680,tv show,the english civil war,"documentary, special interest",amazon
1,583,4.5,as680,tv show,the english civil war,"documentary, special interest",amazon
2,765,5.0,as680,tv show,the english civil war,"documentary, special interest",amazon
3,2116,3.0,as680,tv show,the english civil war,"documentary, special interest",amazon
4,2143,3.0,as680,tv show,the english civil war,"documentary, special interest",amazon

Reordenar mi variable de objetivos

In [29]:
columnas = dfcompl.columns.tolist()
columnas = ['userId', 'movieId', 'type', 'title', 'listed_in', 'plataforma', 'rating']
dfcompl = dfcompl[columnas]
dfcompl.head(2)

,userId,movieId,type,title,listed_in,plataforma,rating
0,1,as680,tv show,the english civil war,"documentary, special interest",amazon,1.0
1,583,as680,tv show,the english civil war,"documentary, special interest",amazon,4.5

Realizo una copia de dfcompl como mejor práctica

In [30]:
df_ml = dfcompl.copy()
df_ml.sample(3)

Creación de una lista de valores de la columna "listed_in
- Esta parte está comentada en esta guía

In [ ]:
# df_ml['listed_in'] = df_ml.listed_in.str.split(' , ')

Rango de verificación de los valores de "rating

In [31]:
print(df_ml['rating'].min())
print(df_ml['rating'].max())
# rating values goes between of 0.5 - 5

0.5
5.0

Preparando mi df con la columna 'userId' 'movieId' 'rating'

In [32]:
df_prepared = df_ml.loc[:,["userId","movieId","rating"]]

Muestreo de 1000000 filas

In [33]:
df_muest = df_prepared.sample(n=1000000, replace=True)

In [34]:
df_muest.head()

          userId movieId  rating
9362722    69738  as4401     3.5
6452135    53268  as4256     3.0
10526316   37461   as228     3.0
2251904   269583  ns4724     3.5
10488530   71590  ns2976     4.0

# Modelando

Codificación de la columna movieId a int

In [39]:
col = df_muest.movieId

# creamos objeto labelencoder y ajustamos la columna
labelE = LabelEncoder()
labelE.fit(col)

#tranformamos la columna
col_transformada = labelE.transform(col)

#lo reemplazamos a show id original
df_muest.movieId = col_transformada
df_muest.head()

          userId  movieId  rating
9362722    69738     3781     3.5
6452135    53268     3619     3.0
10526316   37461     1423     3.0
2251904   269583    18330     3.5
10488530   71590    16387     4.0

Codificación de la columna movieid a int

In [ ]:
# df_prepared = df_ml.loc[:,["userId","movieId","rating"]]

In [ ]:
# df_prepared.head()

In [ ]:
# from scipy.sparse import csr_matrix

# sparse_matrix = csr_matrix(df_prepared.values)

In [41]:
# Convert dataframes to surprise datasets
reader = Reader(line_format='user item rating', rating_scale=(0.5, 5))
data = Dataset.load_from_df(df_muest, reader)

In [42]:
# Build full trainset
data_train_surp = data.build_full_trainset()

# Define the model
svd = SVD()

# Train the model
svd.fit(data_train_surp)

In [43]:
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

In [44]:
predictions = svd.test(testset)

In [45]:
predictions

[Prediction(uid=43558, iid=20574, r_ui=4.0, est=3.2190426559891807, details={'was_impossible': False}),
 Prediction(uid=70364, iid=16080, r_ui=5.0, est=3.6521908680346096, details={'was_impossible': False}),
 Prediction(uid=53352, iid=1307, r_ui=5.0, est=3.83866052331602, details={'was_impossible': False}),
 Prediction(uid=120169, iid=21768, r_ui=5.0, est=4.446494722601759, details={'was_impossible': False}),
 Prediction(uid=74520, iid=4437, r_ui=5.0, est=4.229485098887742, details={'was_impossible': False}),
 Prediction(uid=264720, iid=12773, r_ui=4.0, est=3.6056433147188387, details={'was_impossible': False}),
 Prediction(uid=113568, iid=10190, r_ui=4.0, est=3.8686060809198093, details={'was_impossible': False}),
 Prediction(uid=109775, iid=12222, r_ui=3.0, est=3.4471356425320656, details={'was_impossible': False}),
 Prediction(uid=262210, iid=9701, r_ui=3.0, est=3.1489246935546764, details={'was_impossible': False}),
 Prediction(uid=118292, iid=8616, r_ui=4.0, est=3.990261147202036, details={'was_impossible': False}),
 Prediction(uid=35920, iid=8481, r_ui=2.5, est=2.982688715254654, details={'was_impossible': False}),
 Prediction(uid=1645, iid=19377, r_ui=3.0, est=2.9751398665743416, details={'was_impossible': False}),
 Prediction(uid=11379, iid=6364, r_ui=3.0, est=3.3845736033508764, details={'was_impossible': False}),
 Prediction(uid=25335, iid=14256, r_ui=3.0, est=3.388335768426824, details={'was_impossible': False}),
 Prediction(uid=257010, iid=4969, r_ui=4.0, est=3.974343184458459, details={'was_impossible': False}),
 Prediction(uid=32450, iid=11689, r_ui=2.0, est=2.7946996370636015, details={'was_impossible': False}),
 Prediction(uid=34656, iid=10199, r_ui=2.0, est=3.0865804717929204, details={'was_impossible': False}),
 Prediction(uid=64812, iid=14157, r_ui=4.0, est=3.6998636904454343, details={'was_impossible': False}),
 Prediction(uid=113609, iid=3188, r_ui=3.5, est=3.318000780912587, details={'was_impossible': False}),
 Prediction(uid=68882, iid=16692, r_ui=3.0, est=3.042411826756827, details={'was_impossible': False}),
 Prediction(uid=46771, iid=4149, r_ui=5.0, est=3.9002943554316922, details={'was_impossible': False}),
 Prediction(uid=255904, iid=1407, r_ui=5.0, est=3.9992205668629883, details={'was_impossible': False}),
 Prediction(uid=31773, iid=12031, r_ui=4.0, est=4.559230869452736, details={'was_impossible': False}),
 Prediction(uid=118914, iid=8845, r_ui=4.0, est=3.648585941797098, details={'was_impossible': False}),
 Prediction(uid=119612, iid=4461, r_ui=4.0, est=3.930349722959888, details={'was_impossible': False}),
 Prediction(uid=22252, iid=1160, r_ui=4.0, est=3.467966776117255, details={'was_impossible': False}),
 Prediction(uid=264248, iid=17037, r_ui=2.0, est=2.428662019112628, details={'was_impossible': False}),
 Prediction(uid=6914, iid=10156, r_ui=3.5, est=3.572697302335261, details={'was_impossible': False}),
 Prediction(uid=75131, iid=9264, r_ui=3.0, est=3.4343431517223943, details={'was_impossible': False}),
 Prediction(uid=72886, iid=15929, r_ui=3.0, est=3.212763362774493, details={'was_impossible': False}),
 Prediction(uid=109902, iid=6345, r_ui=4.5, est=4.506948979263062, details={'was_impossible': False}),
 Prediction(uid=61559, iid=22087, r_ui=5.0, est=3.802136057802393, details={'was_impossible': False}),
 Prediction(uid=32711, iid=13046, r_ui=3.0, est=3.1109493081464525, details={'was_impossible': False}),
 Prediction(uid=56847, iid=11855, r_ui=4.0, est=3.727434526712335, details={'was_impossible': False}),
 Prediction(uid=53953, iid=3160, r_ui=2.0, est=3.1172914280429507, details={'was_impossible': False}),
 Prediction(uid=73245, iid=19246, r_ui=4.5, est=4.346262619604675, details={'was_impossible': False}),
 Prediction(uid=38370, iid=10286, r_ui=3.0, est=3.487965692999012, details={'was_impossible': False}),
 Prediction(uid=116185, iid=13512, r_ui=4.5, est=4.093551650579075, details={'was_impossible': False}),
 Prediction(uid=54270, iid=14952, r_ui=4.0, est=4.044062761250958, details={'was_impossible': False}),
 Prediction(uid=117918, iid=9479, r_ui=3.0, est=2.907130755682961, details={'was_impossible': False}),
 Prediction(uid=19436, iid=17313, r_ui=1.0, est=3.0735016877763073, details={'was_impossible': False}),
 Prediction(uid=4785, iid=1139, r_ui=4.5, est=3.703517752275733, details={'was_impossible': False}),
 Prediction(uid=6222, iid=21959, r_ui=5.0, est=3.8061793353840736, details={'was_impossible': False}),
 Prediction(uid=261609, iid=16311, r_ui=4.0, est=3.634498091686826, details={'was_impossible': False}),
 Prediction(uid=72067, iid=997, r_ui=1.0, est=2.855428089109527, details={'was_impossible': False}),
 Prediction(uid=118179, iid=10409, r_ui=4.5, est=3.7422228456665, details={'was_impossible': False}),
 Prediction(uid=891, iid=4293, r_ui=5.0, est=3.6520309488016642, details={'was_impossible': False}),
 Prediction(uid=10389, iid=1785, r_ui=3.0, est=3.5834914146713746, details={'was_impossible': False}),
 Prediction(uid=56567, iid=5655, r_ui=3.0, est=3.4285744570476595, details={'was_impossible': False}),
 Prediction(uid=38465, iid=9980, r_ui=4.0, est=3.872906044380545, details={'was_impossible': False}),
 Prediction(uid=267762, iid=8211, r_ui=4.0, est=3.5743744468860648, details={'was_impossible': False}),
 Prediction(uid=14700, iid=7079, r_ui=3.0, est=3.583416926048504, details={'was_impossible': False}),
 Prediction(uid=13156, iid=8054, r_ui=3.5, est=3.6878520683338563, details={'was_impossible': False}),
 Prediction(uid=251297, iid=7096, r_ui=2.5, est=2.976516591524798, details={'was_impossible': False}),
 Prediction(uid=13518, iid=3994, r_ui=3.0, est=3.8862975234904793, details={'was_impossible': False}),
 Prediction(uid=113200, iid=10861, r_ui=2.0, est=3.080581754546908, details={'was_impossible': False}),
 Prediction(uid=258816, iid=22519, r_ui=4.0, est=3.9428881178087827, details={'was_impossible': False}),
 Prediction(uid=69812, iid=22169, r_ui=3.0, est=3.4879796581311067, details={'was_impossible': False}),
 Prediction(uid=257489, iid=15724, r_ui=4.0, est=3.4301319344134935, details={'was_impossible': False}),
 Prediction(uid=43473, iid=13972, r_ui=3.0, est=3.373468783464791, details={'was_impossible': False}),
 Prediction(uid=109147, iid=3900, r_ui=3.0, est=3.228906704039364, details={'was_impossible': False}),
 Prediction(uid=5332, iid=1231, r_ui=3.0, est=2.998100821214287, details={'was_impossible': False}),
 Prediction(uid=74799, iid=10435, r_ui=4.5, est=4.099309766540054, details={'was_impossible': False}),
 Prediction(uid=30132, iid=20074, r_ui=2.0, est=3.0860602757026943, details={'was_impossible': False}),
 Prediction(uid=56614, iid=10289, r_ui=1.0, est=2.8895532729419964, details={'was_impossible': False}),
 Prediction(uid=43141, iid=17779, r_ui=3.5, est=3.379151650195966, details={'was_impossible': False}),
 Prediction(uid=37060, iid=11433, r_ui=3.0, est=2.745066749177533, details={'was_impossible': False}),
 Prediction(uid=53835, iid=21699, r_ui=4.5, est=3.583871616153055, details={'was_impossible': False}),
 Prediction(uid=37466, iid=7169, r_ui=4.0, est=4.039031631447991, details={'was_impossible': False}),
 Prediction(uid=116390, iid=5986, r_ui=4.0, est=3.642365780568996, details={'was_impossible': False}),
 Prediction(uid=122003, iid=3368, r_ui=4.0, est=3.841652906164221, details={'was_impossible': False}),
 Prediction(uid=54035, iid=13471, r_ui=4.0, est=3.2975431668730777, details={'was_impossible': False}),
 Prediction(uid=47462, iid=77, r_ui=3.0, est=3.298054675479612, details={'was_impossible': False}),
 Prediction(uid=13166, iid=4117, r_ui=2.0, est=2.9353313657185494, details={'was_impossible': False}),
 Prediction(uid=9808, iid=16638, r_ui=4.0, est=3.474343081401239, details={'was_impossible': False}),
 Prediction(uid=4013, iid=9050, r_ui=4.0, est=3.7551718616095324, details={'was_impossible': False}),
 Prediction(uid=4827, iid=20254, r_ui=3.0, est=3.0846976488540157, details={'was_impossible': False}),
 Prediction(uid=26388, iid=22760, r_ui=2.0, est=3.42803302084224, details={'was_impossible': False}),
 Prediction(uid=65876, iid=979, r_ui=4.0, est=3.7091561609986403, details={'was_impossible': False}),
 Prediction(uid=17142, iid=9990, r_ui=2.5, est=3.631025972747476, details={'was_impossible': False}),
 Prediction(uid=268560, iid=13431, r_ui=2.0, est=2.5152508905314908, details={'was_impossible': False}),
 Prediction(uid=66632, iid=529, r_ui=1.5, est=3.128521083969377, details={'was_impossible': False}),
 Prediction(uid=261007, iid=22459, r_ui=1.0, est=2.857717847092019, details={'was_impossible': False}),
 Prediction(uid=32862, iid=18232, r_ui=4.0, est=3.2383366050409075, details={'was_impossible': False}),
 Prediction(uid=22034, iid=17318, r_ui=3.0, est=3.5435373419978333, details={'was_impossible': False}),
 Prediction(uid=112682, iid=6964, r_ui=2.5, est=3.0358428887778177, details={'was_impossible': False}),
 Prediction(uid=255046, iid=9434, r_ui=4.0, est=3.610616559243622, details={'was_impossible': False}),
 Prediction(uid=52611, iid=17674, r_ui=3.5, est=3.671107861376385, details={'was_impossible': False}),
 Prediction(uid=16628, iid=18814, r_ui=2.0, est=2.785745883795104, details={'was_impossible': False}),
 Prediction(uid=264602, iid=17716, r_ui=3.0, est=3.5690691157795102, details={'was_impossible': False}),
 Prediction(uid=259207, iid=6285, r_ui=4.0, est=3.624936508465534, details={'was_impossible': False}),
 Prediction(uid=54872, iid=4478, r_ui=3.0, est=3.5939737708875, details={'was_impossible': False}),
 Prediction(uid=249337, iid=13442, r_ui=2.0, est=2.8475812527579474, details={'was_impossible': False}),
 Prediction(uid=17001, iid=14419, r_ui=3.5, est=3.8641490291160228, details={'was_impossible': False}),
 Prediction(uid=11850, iid=4358, r_ui=2.0, est=2.615881299721842, details={'was_impossible': False}),
 Prediction(uid=47025, iid=21199, r_ui=4.0, est=3.6205872384225044, details={'was_impossible': False}),
 Prediction(uid=270737, iid=15022, r_ui=3.0, est=3.061837890021022, details={'was_impossible': False}),
 Prediction(uid=117634, iid=13025, r_ui=4.5, est=3.519699488928924, details={'was_impossible': False}),
 Prediction(uid=39231, iid=21896, r_ui=3.0, est=3.841083316738481, details={'was_impossible': False}),
 Prediction(uid=66714, iid=7979, r_ui=5.0, est=4.20898776056658, details={'was_impossible': False}),
 Prediction(uid=16271, iid=12974, r_ui=3.0, est=3.723680062285788, details={'was_impossible': False}),
 Prediction(uid=116210, iid=16793, r_ui=4.0, est=4.135245187672547, details={'was_impossible': False}),
 Prediction(uid=58789, iid=3199, r_ui=5.0, est=4.603171384689014, details={'was_impossible': False}),
 Prediction(uid=47561, iid=21058, r_ui=2.5, est=3.1315593151312178, details={'was_impossible': False}),
 Prediction(uid=5936, iid=20261, r_ui=2.0, est=2.5114531114382364, details={'was_impossible': False}),
 Prediction(uid=53592, iid=5543, r_ui=4.0, est=3.7819698552482177, details={'was_impossible': False}),
 Prediction(uid=4411, iid=16145, r_ui=5.0, est=4.620505704090904, details={'was_impossible': False}),
 Prediction(uid=70874, iid=7507, r_ui=2.0, est=3.0295224666754055, details={'was_impossible': False}),
 Prediction(uid=120730, iid=4310, r_ui=4.0, est=3.5586304684289023, details={'was_impossible': False}),
 Prediction(uid=55120, iid=5609, r_ui=3.0, est=3.7625222617248806, details={'was_impossible': False}),
 Prediction(uid=71659, iid=7990, r_ui=3.0, est=3.118949790247788, details={'was_impossible': False}),
 Prediction(uid=8659, iid=5024, r_ui=3.0, est=3.3049017065614406, details={'was_impossible': False}),
 Prediction(uid=21843, iid=18993, r_ui=5.0, est=4.087786465261567, details={'was_impossible': False}),
 Prediction(uid=24905, iid=22493, r_ui=5.0, est=3.6238366434794815, details={'was_impossible': False}),
 Prediction(uid=11569, iid=39, r_ui=4.5, est=3.9211046793161364, details={'was_impossible': False}),
 Prediction(uid=110112, iid=21350, r_ui=3.5, est=3.5725718722332207, details={'was_impossible': False}),
 Prediction(uid=54478, iid=6496, r_ui=3.5, est=3.1673881745502572, details={'was_impossible': False}),
 Prediction(uid=33165, iid=9876, r_ui=4.0, est=3.5958228727417363, details={'was_impossible': False}),
 Prediction(uid=6894, iid=4548, r_ui=3.5, est=3.8076020535857467, details={'was_impossible': False}),
 Prediction(uid=55252, iid=20008, r_ui=1.0, est=2.71520243770257, details={'was_impossible': False}),
 Prediction(uid=5695, iid=5228, r_ui=2.0, est=2.916687773386246, details={'was_impossible': False}),
 Prediction(uid=13740, iid=15974, r_ui=4.0, est=3.600000153179184, details={'was_impossible': False}),
 Prediction(uid=60727, iid=22666, r_ui=4.0, est=3.5827366476382587, details={'was_impossible': False}),
 Prediction(uid=48049, iid=19537, r_ui=3.0, est=2.968376774699725, details={'was_impossible': False}),
 Prediction(uid=59686, iid=11667, r_ui=2.5, est=3.255208390643239, details={'was_impossible': False}),
 Prediction(uid=10991, iid=10337, r_ui=4.0, est=3.7226947023853296, details={'was_impossible': False}),
 Prediction(uid=268234, iid=19961, r_ui=5.0, est=4.156987290745241, details={'was_impossible': False}),
 Prediction(uid=260466, iid=18353, r_ui=2.5, est=2.789562798538907, details={'was_impossible': False}),
 Prediction(uid=123994, iid=12171, r_ui=2.5, est=2.7432608205369444, details={'was_impossible': False}),
 Prediction(uid=57566, iid=20345, r_ui=1.0, est=2.658525888386071, details={'was_impossible': False}),
 Prediction(uid=51361, iid=4240, r_ui=3.5, est=3.780350376686137, details={'was_impossible': False}),
 Prediction(uid=22903, iid=16717, r_ui=4.0, est=3.7041032911893055, details={'was_impossible': False}),
 Prediction(uid=33192, iid=21984, r_ui=5.0, est=4.2942630367208405, details={'was_impossible': False}),
 Prediction(uid=256434, iid=9875, r_ui=2.0, est=3.0565454152969838, details={'was_impossible': False}),
 Prediction(uid=254547, iid=21306, r_ui=4.5, est=4.343321007402026, details={'was_impossible': False}),
 Prediction(uid=1009, iid=21572, r_ui=3.0, est=3.1857868894819426, details={'was_impossible': False}),
 Prediction(uid=261643, iid=16102, r_ui=4.5, est=4.275174979283982, details={'was_impossible': False}),
 Prediction(uid=23455, iid=13146, r_ui=5.0, est=3.8645246711934025, details={'was_impossible': False}),
 Prediction(uid=49249, iid=19702, r_ui=4.0, est=3.547249398238905, details={'was_impossible': False}),
 Prediction(uid=264742, iid=3436, r_ui=4.5, est=4.105373689258676, details={'was_impossible': False}),
 Prediction(uid=265580, iid=353, r_ui=3.5, est=3.3047870359391265, details={'was_impossible': False}),
 Prediction(uid=64759, iid=7510, r_ui=3.0, est=3.699584071807169, details={'was_impossible': False}),
 Prediction(uid=32320, iid=21767, r_ui=4.0, est=3.6853826778904923, details={'was_impossible': False}),
 Prediction(uid=46877, iid=2992, r_ui=4.0, est=4.012983631263164, details={'was_impossible': False}),
 Prediction(uid=50962, iid=12275, r_ui=4.0, est=3.4359844403658766, details={'was_impossible': False}),
 Prediction(uid=5983, iid=19241, r_ui=4.0, est=3.93579665500628, details={'was_impossible': False}),
 Prediction(uid=69420, iid=20864, r_ui=3.0, est=3.3056986524888687, details={'was_impossible': False}),
 Prediction(uid=46393, iid=2968, r_ui=3.0, est=3.7959404018376617, details={'was_impossible': False}),
 Prediction(uid=118046, iid=9352, r_ui=5.0, est=3.9820884143318267, details={'was_impossible': False}),
 Prediction(uid=113843, iid=7549, r_ui=1.0, est=2.7768391075166887, details={'was_impossible': False}),
 Prediction(uid=262784, iid=22128, r_ui=2.0, est=3.133196232130997, details={'was_impossible': False}),
 Prediction(uid=49811, iid=21198, r_ui=4.5, est=3.764094863316404, details={'was_impossible': False}),
 Prediction(uid=261202, iid=7685, r_ui=5.0, est=4.0108545898420225, details={'was_impossible': False}),
 Prediction(uid=66405, iid=22432, r_ui=4.0, est=3.8465430249974286, details={'was_impossible': False}),
 Prediction(uid=5446, iid=9034, r_ui=5.0, est=4.321920933724952, details={'was_impossible': False}),
 Prediction(uid=10485, iid=18671, r_ui=4.0, est=3.4206714509174327, details={'was_impossible': False}),
 Prediction(uid=113999, iid=4683, r_ui=3.0, est=3.5147807045597914, details={'was_impossible': False}),
 Prediction(uid=41273, iid=20839, r_ui=2.0, est=3.372133851900575, details={'was_impossible': False}),
 Prediction(uid=108725, iid=6257, r_ui=2.5, est=3.269756996020155, details={'was_impossible': False}),
 Prediction(uid=46527, iid=3973, r_ui=4.0, est=3.859183938625132, details={'was_impossible': False}),
 Prediction(uid=270776, iid=22864, r_ui=4.0, est=4.517977776933002, details={'was_impossible': False}),
 Prediction(uid=14276, iid=1702, r_ui=3.0, est=3.3431141041211934, details={'was_impossible': False}),
 Prediction(uid=73589, iid=1038, r_ui=3.0, est=3.765378887181983, details={'was_impossible': False}),
 Prediction(uid=260210, iid=4156, r_ui=4.5, est=4.266704363472242, details={'was_impossible': False}),
 Prediction(uid=7662, iid=3543, r_ui=4.0, est=3.9209709825658297, details={'was_impossible': False}),
 Prediction(uid=109395, iid=154, r_ui=4.5, est=4.204671864459781, details={'was_impossible': False}),
 Prediction(uid=256755, iid=4577, r_ui=5.0, est=4.016363967531867, details={'was_impossible': False}),
 Prediction(uid=42340, iid=4045, r_ui=2.0, est=2.7171121909490736, details={'was_impossible': False}),
 Prediction(uid=7862, iid=10207, r_ui=4.0, est=3.358968399597944, details={'was_impossible': False}),
 Prediction(uid=266991, iid=5985, r_ui=4.0, est=3.6700732353841645, details={'was_impossible': False}),
 Prediction(uid=40829, iid=17175, r_ui=3.5, est=3.3812967719117974, details={'was_impossible': False}),
 Prediction(uid=267915, iid=11576, r_ui=0.5, est=2.9672385166480946, details={'was_impossible': False}),
 Prediction(uid=123017, iid=10959, r_ui=4.0, est=3.90573549615557, details={'was_impossible': False}),
 Prediction(uid=54278, iid=10627, r_ui=4.5, est=4.151241819285091, details={'was_impossible': False}),
 Prediction(uid=77327, iid=17414, r_ui=4.0, est=3.6370522208595806, details={'was_impossible': False}),
 Prediction(uid=9817, iid=21366, r_ui=4.0, est=3.9029367048634147, details={'was_impossible': False}),
 Prediction(uid=251794, iid=4197, r_ui=1.5, est=2.2843768166575265, details={'was_impossible': False}),
 Prediction(uid=252270, iid=19310, r_ui=4.5, est=3.578879749798515, details={'was_impossible': False}),
 Prediction(uid=66544, iid=4353, r_ui=4.0, est=3.4543278254547656, details={'was_impossible': False}),
 Prediction(uid=265085, iid=11286, r_ui=2.5, est=3.14806156811167, details={'was_impossible': False}),
 Prediction(uid=29764, iid=14877, r_ui=4.0, est=4.085789647815648, details={'was_impossible': False}),
 Prediction(uid=9600, iid=21360, r_ui=3.0, est=2.9259951743691666, details={'was_impossible': False}),
 Prediction(uid=270374, iid=19615, r_ui=2.0, est=3.5192518086891167, details={'was_impossible': False}),
 Prediction(uid=109559, iid=8016, r_ui=1.0, est=2.956769703099698, details={'was_impossible': False}),
 Prediction(uid=49309, iid=10609, r_ui=3.5, est=3.0225061708709213, details={'was_impossible': False}),
 Prediction(uid=71007, iid=21903, r_ui=4.0, est=3.490377168031969, details={'was_impossible': False}),
 Prediction(uid=39890, iid=18963, r_ui=3.0, est=3.416896428172765, details={'was_impossible': False}),
 Prediction(uid=111206, iid=22769, r_ui=5.0, est=3.635800041537508, details={'was_impossible': False}),
 Prediction(uid=251250, iid=14727, r_ui=4.0, est=3.6680359343570625, details={'was_impossible': False}),
 Prediction(uid=21958, iid=17639, r_ui=4.5, est=4.361208923498351, details={'was_impossible': False}),
 Prediction(uid=11043, iid=10991, r_ui=4.0, est=3.884860148599576, details={'was_impossible': False}),
 Prediction(uid=11567, iid=17793, r_ui=4.0, est=3.542742458787178, details={'was_impossible': False}),
 Prediction(uid=17525, iid=26, r_ui=3.0, est=3.312645456430485, details={'was_impossible': False}),

In [46]:
svd.predict(356,567,4)

Prediction(uid=356, iid=567, r_ui=4, est=3.729538794417126, details={'was_impossible': False})