Importo las librerías para trabajar

In [1]:
import pandas as pd
import requests
import shutil
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import LabelEncoder
from scipy import sparse
from surprise import Dataset, Reader
from surprise import SVD
from surprise import accuracy
from surprise.model_selection import train_test_split
import gradio as gr

In [2]:
dfml=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/ML_ETL_plataformas.csv')

In [3]:
dfmlr1=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/1.csv')
dfmlr2=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/2.csv')
dfmlr3=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/3.csv')
dfmlr4=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/4.csv')
dfmlr5=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/5.csv')
dfmlr6=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/6.csv')
dfmlr7=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/7.csv')
dfmlr8=pd.read_csv(r'/Users/herminiaaguirre/Desktop/Henry/Proyectos varios/4.PI/MLOps/datasets/ratings/8.csv')

In [4]:
dfmlr=(pd.concat([dfmlr1,dfmlr2,dfmlr3,dfmlr4,dfmlr5,dfmlr6,dfmlr7,dfmlr8], axis=0))

Elimino la columna 'timespan' de df_users porque no la vamos a utilizar

In [5]:
dfmlr = dfmlr.drop(['timestamp'], axis=1)

In [6]:
dfml.head(1)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,plataforma,duration_int,duration_type,score
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30 00:00:00,2014,G,113 min,"comedy, drama",a small fishing village must procure a local d...,amazon,113,min,3.549127

Elimino columnas no relevantes para el análisis

In [7]:
dfml= dfml.drop(['show_id','director','cast','country','date_added','release_year','rating','duration','description','duration_int','duration_type','score'], axis=1)

In [8]:
dfml.head(1)

    id   type                title      listed_in plataforma
0  as1  movie  the grand seduction  comedy, drama     amazon

Cambio de nombre de la columna 'id' a 'movieId'

In [9]:
dfml = dfml.rename(columns={'id': 'movieId'})
# We have now the same colum 'movieId' for both dfs

In [10]:
dfml.head(2)

  movieId   type                 title             listed_in plataforma
0     as1  movie   the grand seduction         comedy, drama     amazon
1     as2  movie  take care good night  drama, international     amazon

Uno los dos df

In [11]:
dfcompl = pd.merge(left=dfmlr,right=dfml)

In [12]:
dfcompl.shape
# we have 11024289 rows

(11024289, 7)

In [13]:
dfcompl.head(5)

,userId,rating,movieId,type,title,listed_in,plataforma
0,1,1.0,as680,tv show,the english civil war,"documentary, special interest",amazon
1,583,4.5,as680,tv show,the english civil war,"documentary, special interest",amazon
2,765,5.0,as680,tv show,the english civil war,"documentary, special interest",amazon
3,2116,3.0,as680,tv show,the english civil war,"documentary, special interest",amazon
4,2143,3.0,as680,tv show,the english civil war,"documentary, special interest",amazon

Reordeno la variable de objetivo

In [14]:
columnas = dfcompl.columns.tolist()
columnas = ['userId', 'movieId', 'type', 'title', 'listed_in', 'plataforma', 'rating']
dfcompl = dfcompl[columnas]
dfcompl.head(2)

,userId,movieId,type,title,listed_in,plataforma,rating
0,1,as680,tv show,the english civil war,"documentary, special interest",amazon,1.0
1,583,as680,tv show,the english civil war,"documentary, special interest",amazon,4.5

Realizo una copia de dfcompl como mejor práctica

In [15]:
df_ml = dfcompl.copy()
df_ml.sample(3)

,userId,movieId,type,title,listed_in,plataforma,rating
5427969,66440,ns3246,tv show,singapore social,"international tv shows, reality tv",netflix,4.0
8335965,6201,as1682,tv show,michael jackson: the ultimate icon,tv shows,amazon,5.0
2357561,436,ns7801,tv show,psiconautas,"international tv shows, spanish-language tv sh...",netflix,2.5

Creo una lista de valores de la columna 'listed_in'

In [17]:
df_ml['listed_in'] = df_ml.listed_in.str.split(' , ')

Rango de verificación de los valores de 'rating'

In [18]:
print(df_ml['rating'].min())
print(df_ml['rating'].max())
# rating values goes between of 0.5 - 5

0.5
5.0

Preparo el df con la columna 'userId' 'movieId' 'rating'

In [19]:
df_prepared = df_ml.loc[:,["userId","movieId","rating"]]

Utilizo una muestra de 1M filas

In [20]:
df_muest = df_prepared.sample(n=1000000, replace=True)

In [21]:
df_muest.head()

          userId movieId  rating
2824810    32442  as8972     0.5
2196932    19837  as4089     5.0
10099237   10911  as2630     1.0
1100215    60078   ns968     4.0
6474929    28855  as7240     3.0

Modelado

Realizo una codificación de la columna movieId a int

In [22]:
col = df_muest.movieId

# creamos objeto labelencoder y ajustamos la columna
labelE = LabelEncoder()
labelE.fit(col)

#tranformamos la columna
col_transformada = labelE.transform(col)

#lo reemplazamos a show id original
df_muest.movieId = col_transformada
df_muest.head()

          userId  movieId  rating
2824810    32442     8858     0.5
2196932    19837     3433     5.0
10099237   10911     1813     1.0
1100215    60078    22963     4.0
6474929    28855     6935     3.0

In [ ]:
# df_prepared = df_ml.loc[:,["userId","movieId","rating"]]

In [ ]:
# df_prepared.head()

In [ ]:
# from scipy.sparse import csr_matrix

# sparse_matrix = csr_matrix(df_prepared.values)

Convierto los df a surprise datasets

In [23]:
reader = Reader(line_format='user item rating', rating_scale=(0.5, 5))
data = Dataset.load_from_df(df_muest, reader)

In [24]:
# Build full trainset
data_train_surp = data.build_full_trainset()

# Define the model
svd = SVD()

# Train the model
svd.fit(data_train_surp)

In [25]:
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

In [26]:
predictions = svd.test(testset)

In [27]:
predictions

[Prediction(uid=119410, iid=11811, r_ui=3.0, est=3.3035782375691567, details={'was_impossible': False}),
 Prediction(uid=54005, iid=4396, r_ui=4.5, est=3.7272781442072405, details={'was_impossible': False}),
 Prediction(uid=12306, iid=13250, r_ui=3.0, est=3.1299017664188535, details={'was_impossible': False}),
 Prediction(uid=12962, iid=22181, r_ui=3.0, est=2.955067219335197, details={'was_impossible': False}),
 Prediction(uid=115715, iid=11436, r_ui=4.0, est=3.917206217232953, details={'was_impossible': False}),
 Prediction(uid=33940, iid=12026, r_ui=3.5, est=2.784460490879487, details={'was_impossible': False}),
 Prediction(uid=25086, iid=20899, r_ui=4.0, est=3.9172474131200636, details={'was_impossible': False}),
 Prediction(uid=113525, iid=10627, r_ui=3.0, est=3.674915887921005, details={'was_impossible': False}),
 Prediction(uid=30394, iid=5692, r_ui=3.0, est=3.5374337407594316, details={'was_impossible': False}),
 Prediction(uid=260233, iid=3620, r_ui=3.0, est=3.3280731606932927, details={'was_impossible': False}),
 Prediction(uid=772, iid=8795, r_ui=3.0, est=3.196295116271142, details={'was_impossible': False}),
 Prediction(uid=7570, iid=307, r_ui=3.0, est=2.868118514219288, details={'was_impossible': False}),
 Prediction(uid=19264, iid=9249, r_ui=4.5, est=3.1488714795162354, details={'was_impossible': False}),
 Prediction(uid=6823, iid=18391, r_ui=5.0, est=3.6572249857966597, details={'was_impossible': False}),
 Prediction(uid=264274, iid=16942, r_ui=4.0, est=3.849541815773239, details={'was_impossible': False}),
 Prediction(uid=40760, iid=4286, r_ui=2.5, est=3.141696271109828, details={'was_impossible': False}),
 Prediction(uid=31607, iid=21981, r_ui=4.0, est=3.0897876931632657, details={'was_impossible': False}),
 Prediction(uid=52856, iid=3103, r_ui=5.0, est=4.131298518633524, details={'was_impossible': False}),
 Prediction(uid=258804, iid=12280, r_ui=3.0, est=3.5097515608302707, details={'was_impossible': False}),
 Prediction(uid=34683, iid=12494, r_ui=3.0, est=3.2067128173304056, details={'was_impossible': False}),
 Prediction(uid=42485, iid=20539, r_ui=0.5, est=1.7085719921077265, details={'was_impossible': False}),
 Prediction(uid=47154, iid=12754, r_ui=5.0, est=4.125886895044218, details={'was_impossible': False}),
 Prediction(uid=261561, iid=20393, r_ui=3.5, est=3.4478308251637326, details={'was_impossible': False}),
 Prediction(uid=75557, iid=21992, r_ui=4.0, est=3.719124243274303, details={'was_impossible': False}),
 Prediction(uid=44807, iid=7295, r_ui=4.5, est=3.9647394205760182, details={'was_impossible': False}),
 Prediction(uid=8255, iid=14362, r_ui=4.5, est=3.9695890142383927, details={'was_impossible': False}),
 Prediction(uid=112493, iid=13055, r_ui=3.0, est=3.118888004565105, details={'was_impossible': False}),
 Prediction(uid=45686, iid=14954, r_ui=4.0, est=3.623586319092138, details={'was_impossible': False}),
 Prediction(uid=18542, iid=7396, r_ui=2.0, est=3.217094802666059, details={'was_impossible': False}),
 Prediction(uid=21635, iid=14602, r_ui=4.0, est=3.637642684669529, details={'was_impossible': False}),
 Prediction(uid=12562, iid=8964, r_ui=3.0, est=3.795029863974312, details={'was_impossible': False}),
 Prediction(uid=37204, iid=19925, r_ui=3.0, est=3.598262744761924, details={'was_impossible': False}),
 Prediction(uid=836, iid=16943, r_ui=4.0, est=3.7518481770665044, details={'was_impossible': False}),
 Prediction(uid=269404, iid=13849, r_ui=4.5, est=3.921606989463947, details={'was_impossible': False}),
 Prediction(uid=263796, iid=16295, r_ui=5.0, est=4.287667170044963, details={'was_impossible': False}),
 Prediction(uid=123836, iid=18978, r_ui=2.0, est=3.241833019302081, details={'was_impossible': False}),
 Prediction(uid=71703, iid=12193, r_ui=4.0, est=3.217182237597406, details={'was_impossible': False}),
 Prediction(uid=75464, iid=13280, r_ui=3.0, est=2.845364788886297, details={'was_impossible': False}),
 Prediction(uid=270211, iid=17059, r_ui=3.0, est=3.5388491597615506, details={'was_impossible': False}),
 Prediction(uid=75464, iid=9136, r_ui=2.0, est=2.895427090831424, details={'was_impossible': False}),
 Prediction(uid=27502, iid=21874, r_ui=4.0, est=3.8966272546006726, details={'was_impossible': False}),
 Prediction(uid=115086, iid=22921, r_ui=4.0, est=3.4746302261354565, details={'was_impossible': False}),
 Prediction(uid=263891, iid=22625, r_ui=3.5, est=3.3096461570641997, details={'was_impossible': False}),
 Prediction(uid=5523, iid=15553, r_ui=3.0, est=3.4542431255106276, details={'was_impossible': False}),
 Prediction(uid=41786, iid=9299, r_ui=3.5, est=4.009211622648103, details={'was_impossible': False}),
 Prediction(uid=72299, iid=15207, r_ui=3.5, est=3.9209836525680664, details={'was_impossible': False}),
 Prediction(uid=29520, iid=7829, r_ui=4.5, est=3.9548716809326327, details={'was_impossible': False}),
 Prediction(uid=253509, iid=4331, r_ui=4.5, est=3.927090869553215, details={'was_impossible': False}),
 Prediction(uid=251181, iid=7092, r_ui=1.5, est=3.6504955922550817, details={'was_impossible': False}),
 Prediction(uid=262914, iid=7241, r_ui=5.0, est=4.223545619005544, details={'was_impossible': False}),
 Prediction(uid=34712, iid=4978, r_ui=1.0, est=1.8995885985373204, details={'was_impossible': False}),
 Prediction(uid=44055, iid=2476, r_ui=3.5, est=3.3144732616983172, details={'was_impossible': False}),
 Prediction(uid=124018, iid=1716, r_ui=2.0, est=2.990016738992915, details={'was_impossible': False}),
 Prediction(uid=36448, iid=1665, r_ui=3.5, est=3.246399609022573, details={'was_impossible': False}),
 Prediction(uid=6512, iid=22844, r_ui=4.5, est=3.448311792477236, details={'was_impossible': False}),
 Prediction(uid=14721, iid=5665, r_ui=2.0, est=3.5921301603023927, details={'was_impossible': False}),
 Prediction(uid=121432, iid=10649, r_ui=3.5, est=3.894267252540894, details={'was_impossible': False}),
 Prediction(uid=117008, iid=4785, r_ui=3.0, est=3.4069695704198293, details={'was_impossible': False}),
 Prediction(uid=113279, iid=12651, r_ui=5.0, est=3.7372735892231064, details={'was_impossible': False}),
 Prediction(uid=112475, iid=14481, r_ui=1.0, est=2.2348169299890617, details={'was_impossible': False}),
 Prediction(uid=43993, iid=5703, r_ui=4.5, est=3.6924728381379035, details={'was_impossible': False}),
 Prediction(uid=114825, iid=12057, r_ui=4.0, est=3.431193998492588, details={'was_impossible': False}),
 Prediction(uid=40073, iid=5699, r_ui=4.5, est=3.507683251594305, details={'was_impossible': False}),
 Prediction(uid=113135, iid=17951, r_ui=5.0, est=3.3884788647610264, details={'was_impossible': False}),
 Prediction(uid=49794, iid=8165, r_ui=4.0, est=3.0855850854041225, details={'was_impossible': False}),
 Prediction(uid=269250, iid=5052, r_ui=4.0, est=3.5238570234450006, details={'was_impossible': False}),
 Prediction(uid=42609, iid=5526, r_ui=3.5, est=3.599922300486152, details={'was_impossible': False}),
 Prediction(uid=30919, iid=5698, r_ui=3.0, est=2.7173935277698678, details={'was_impossible': False}),
 Prediction(uid=71175, iid=2698, r_ui=2.0, est=3.4456872982688584, details={'was_impossible': False}),
 Prediction(uid=270769, iid=10911, r_ui=3.0, est=3.008351534584199, details={'was_impossible': False}),
 Prediction(uid=25224, iid=19735, r_ui=5.0, est=3.458723987417094, details={'was_impossible': False}),
 Prediction(uid=1762, iid=15873, r_ui=3.0, est=3.8960817345566676, details={'was_impossible': False}),
 Prediction(uid=262753, iid=12774, r_ui=3.0, est=3.671964277222323, details={'was_impossible': False}),
 Prediction(uid=11137, iid=8028, r_ui=4.0, est=3.1650843751971873, details={'was_impossible': False}),
 Prediction(uid=2680, iid=12094, r_ui=4.0, est=3.4579134787602523, details={'was_impossible': False}),
 Prediction(uid=40347, iid=7079, r_ui=4.0, est=3.780466723107366, details={'was_impossible': False}),
 Prediction(uid=10637, iid=16110, r_ui=4.0, est=3.4993362110521327, details={'was_impossible': False}),
 Prediction(uid=117398, iid=19291, r_ui=3.0, est=3.489835022599637, details={'was_impossible': False}),
 Prediction(uid=55158, iid=13383, r_ui=4.5, est=3.852292094916301, details={'was_impossible': False}),
 Prediction(uid=55559, iid=7626, r_ui=5.0, est=3.8618655231606116, details={'was_impossible': False}),
 Prediction(uid=46776, iid=19062, r_ui=4.0, est=4.006070773800042, details={'was_impossible': False}),
 Prediction(uid=74177, iid=6127, r_ui=2.0, est=3.2179569994901214, details={'was_impossible': False}),
 Prediction(uid=57901, iid=13369, r_ui=5.0, est=4.302455158199593, details={'was_impossible': False}),
 Prediction(uid=73468, iid=17451, r_ui=2.5, est=3.5256167349678234, details={'was_impossible': False}),
 Prediction(uid=22396, iid=9841, r_ui=2.0, est=2.895857718353814, details={'was_impossible': False}),
 Prediction(uid=265199, iid=12976, r_ui=3.0, est=3.557647573757529, details={'was_impossible': False}),
 Prediction(uid=250368, iid=10650, r_ui=3.0, est=3.7182655878137614, details={'was_impossible': False}),
 Prediction(uid=4387, iid=9585, r_ui=2.0, est=3.046697767913235, details={'was_impossible': False}),
 Prediction(uid=9547, iid=5471, r_ui=5.0, est=4.183076565241548, details={'was_impossible': False}),
 Prediction(uid=266449, iid=10176, r_ui=3.0, est=3.6628569171689787, details={'was_impossible': False}),
 Prediction(uid=268956, iid=11136, r_ui=4.0, est=4.074767000967148, details={'was_impossible': False}),
 Prediction(uid=257532, iid=19440, r_ui=4.5, est=3.643510518751052, details={'was_impossible': False}),
 Prediction(uid=31897, iid=11879, r_ui=2.5, est=2.4360113770739145, details={'was_impossible': False}),
 Prediction(uid=71581, iid=8026, r_ui=3.5, est=3.485608165374081, details={'was_impossible': False}),
 Prediction(uid=24024, iid=11568, r_ui=5.0, est=3.8555604415020612, details={'was_impossible': False}),
 Prediction(uid=18679, iid=4398, r_ui=3.0, est=3.622476997463592, details={'was_impossible': False}),
 Prediction(uid=112179, iid=5757, r_ui=2.5, est=2.9206842869289638, details={'was_impossible': False}),
 Prediction(uid=7221, iid=11714, r_ui=3.0, est=3.667457321137384, details={'was_impossible': False}),
 Prediction(uid=28939, iid=4744, r_ui=3.0, est=3.463402025008353, details={'was_impossible': False}),
 Prediction(uid=12782, iid=4063, r_ui=3.0, est=3.0854644023656066, details={'was_impossible': False}),
 Prediction(uid=258060, iid=11080, r_ui=4.0, est=3.924651118512342, details={'was_impossible': False}),
 Prediction(uid=117842, iid=20542, r_ui=4.0, est=3.7889311424726158, details={'was_impossible': False}),
 Prediction(uid=43433, iid=6221, r_ui=2.5, est=3.3430592688958622, details={'was_impossible': False}),
 Prediction(uid=58170, iid=15741, r_ui=5.0, est=4.1773770069605165, details={'was_impossible': False}),
 Prediction(uid=28379, iid=11555, r_ui=4.0, est=3.4997371364476777, details={'was_impossible': False}),
 Prediction(uid=113461, iid=6723, r_ui=1.0, est=2.5382565459571733, details={'was_impossible': False}),
 Prediction(uid=266688, iid=14932, r_ui=4.0, est=3.745782440813801, details={'was_impossible': False}),
 Prediction(uid=123018, iid=12732, r_ui=4.0, est=3.7161976151265024, details={'was_impossible': False}),
 Prediction(uid=33673, iid=9167, r_ui=3.5, est=3.51922863156314, details={'was_impossible': False}),
 Prediction(uid=64577, iid=19259, r_ui=3.0, est=2.7855074011755767, details={'was_impossible': False}),
 Prediction(uid=51466, iid=1266, r_ui=3.5, est=3.5505366197294035, details={'was_impossible': False}),
 Prediction(uid=267624, iid=17885, r_ui=4.5, est=4.127077981762826, details={'was_impossible': False}),
 Prediction(uid=30025, iid=20537, r_ui=3.0, est=3.0179645909400126, details={'was_impossible': False}),
 Prediction(uid=10717, iid=10610, r_ui=4.5, est=4.267595461555993, details={'was_impossible': False}),
 Prediction(uid=32657, iid=19316, r_ui=4.0, est=3.4981878561494097, details={'was_impossible': False}),
 Prediction(uid=10448, iid=710, r_ui=4.0, est=2.712975778472376, details={'was_impossible': False}),
 Prediction(uid=3166, iid=18787, r_ui=5.0, est=3.627128833810288, details={'was_impossible': False}),
 Prediction(uid=24537, iid=6270, r_ui=4.0, est=4.159326474690397, details={'was_impossible': False}),
 Prediction(uid=120791, iid=22916, r_ui=2.0, est=2.4632954257435467, details={'was_impossible': False}),
 Prediction(uid=111026, iid=8125, r_ui=3.0, est=3.5652199052897933, details={'was_impossible': False}),
 Prediction(uid=53831, iid=6222, r_ui=2.0, est=3.4057177770922213, details={'was_impossible': False}),
 Prediction(uid=43540, iid=22825, r_ui=2.0, est=2.649627374469342, details={'was_impossible': False}),
 Prediction(uid=24082, iid=1037, r_ui=5.0, est=4.16875432944202, details={'was_impossible': False}),
 Prediction(uid=68043, iid=7896, r_ui=4.0, est=4.34997876638831, details={'was_impossible': False}),
 Prediction(uid=6978, iid=6850, r_ui=4.5, est=4.662759013611099, details={'was_impossible': False}),
 Prediction(uid=62715, iid=7554, r_ui=4.0, est=3.852160292354948, details={'was_impossible': False}),
 Prediction(uid=114773, iid=16708, r_ui=2.0, est=3.119315852059808, details={'was_impossible': False}),
 Prediction(uid=257703, iid=17170, r_ui=2.0, est=3.036628153738765, details={'was_impossible': False}),
 Prediction(uid=45811, iid=2981, r_ui=3.0, est=2.975329724182911, details={'was_impossible': False}),
 Prediction(uid=110808, iid=18388, r_ui=3.0, est=2.876061076395703, details={'was_impossible': False}),
 Prediction(uid=18491, iid=2098, r_ui=5.0, est=3.866702358531547, details={'was_impossible': False}),
 Prediction(uid=262621, iid=13520, r_ui=3.0, est=3.4437334938952704, details={'was_impossible': False}),
 Prediction(uid=270246, iid=18817, r_ui=5.0, est=4.347351999185149, details={'was_impossible': False}),
 Prediction(uid=56996, iid=21093, r_ui=4.0, est=3.6132142201739446, details={'was_impossible': False}),
 Prediction(uid=49410, iid=18806, r_ui=2.0, est=3.269285780370201, details={'was_impossible': False}),
 Prediction(uid=252193, iid=212, r_ui=5.0, est=4.126448876285377, details={'was_impossible': False}),
 Prediction(uid=118459, iid=1079, r_ui=1.0, est=2.7346265067307933, details={'was_impossible': False}),
 Prediction(uid=47713, iid=6152, r_ui=5.0, est=3.5625019660533863, details={'was_impossible': False}),
 Prediction(uid=252534, iid=13402, r_ui=4.0, est=3.5710733886549635, details={'was_impossible': False}),
 Prediction(uid=23167, iid=18257, r_ui=4.0, est=4.074263402001761, details={'was_impossible': False}),
 Prediction(uid=32984, iid=18438, r_ui=2.5, est=2.790271821192601, details={'was_impossible': False}),
 Prediction(uid=738, iid=13803, r_ui=4.5, est=3.602630423424122, details={'was_impossible': False}),
 Prediction(uid=251785, iid=21951, r_ui=0.5, est=2.424888888356139, details={'was_impossible': False}),
 Prediction(uid=7956, iid=12668, r_ui=2.0, est=3.0243429493374014, details={'was_impossible': False}),
 Prediction(uid=25784, iid=1128, r_ui=2.0, est=2.7957256728833153, details={'was_impossible': False}),
 Prediction(uid=13373, iid=16080, r_ui=2.0, est=2.5944690582576646, details={'was_impossible': False}),
 Prediction(uid=254912, iid=9196, r_ui=4.0, est=3.224633896589113, details={'was_impossible': False}),
 Prediction(uid=110195, iid=13098, r_ui=1.0, est=2.796565105997325, details={'was_impossible': False}),
 Prediction(uid=9040, iid=18382, r_ui=3.0, est=3.0384062145587625, details={'was_impossible': False}),
 Prediction(uid=119003, iid=4630, r_ui=3.0, est=3.498365188321825, details={'was_impossible': False}),
 Prediction(uid=36025, iid=4373, r_ui=1.0, est=1.9792431791475638, details={'was_impossible': False}),
 Prediction(uid=2995, iid=10520, r_ui=4.0, est=4.250836604604351, details={'was_impossible': False}),
 Prediction(uid=257857, iid=11691, r_ui=4.0, est=3.7958218676024553, details={'was_impossible': False}),
 Prediction(uid=71526, iid=7103, r_ui=2.0, est=2.6679285363787324, details={'was_impossible': False}),
 Prediction(uid=63617, iid=15161, r_ui=4.0, est=4.060272839116233, details={'was_impossible': False}),
 Prediction(uid=40653, iid=6929, r_ui=4.0, est=3.3418134593024558, details={'was_impossible': False}),
 Prediction(uid=70466, iid=10400, r_ui=4.0, est=3.7448901509235686, details={'was_impossible': False}),
 Prediction(uid=70077, iid=564, r_ui=5.0, est=4.323795309259251, details={'was_impossible': False}),
 Prediction(uid=263700, iid=21423, r_ui=4.0, est=3.231076294764634, details={'was_impossible': False}),
 Prediction(uid=28417, iid=9832, r_ui=4.5, est=3.434057648249743, details={'was_impossible': False}),
 Prediction(uid=117801, iid=18849, r_ui=5.0, est=3.903788481884602, details={'was_impossible': False}),
 Prediction(uid=54770, iid=1513, r_ui=5.0, est=3.6806187570667066, details={'was_impossible': False}),
 Prediction(uid=9348, iid=2588, r_ui=2.0, est=3.1792942850110615, details={'was_impossible': False}),
 Prediction(uid=255933, iid=1924, r_ui=2.0, est=2.977137403361738, details={'was_impossible': False}),
 Prediction(uid=33484, iid=18711, r_ui=4.5, est=4.092390971226101, details={'was_impossible': False}),
 Prediction(uid=268380, iid=18920, r_ui=4.0, est=4.051515308634889, details={'was_impossible': False}),
 Prediction(uid=258091, iid=14578, r_ui=4.0, est=3.897634800347414, details={'was_impossible': False}),
 Prediction(uid=21302, iid=3996, r_ui=4.0, est=3.839852330027491, details={'was_impossible': False}),
 Prediction(uid=62085, iid=7610, r_ui=2.0, est=3.3685582158691396, details={'was_impossible': False}),
 Prediction(uid=117432, iid=1710, r_ui=2.5, est=3.1855626746301797, details={'was_impossible': False}),
 Prediction(uid=265662, iid=14956, r_ui=4.0, est=3.40856761439032, details={'was_impossible': False}),
 Prediction(uid=253951, iid=13563, r_ui=3.0, est=3.7687075104804935, details={'was_impossible': False}),
 Prediction(uid=34535, iid=1643, r_ui=4.0, est=3.957793403682979, details={'was_impossible': False}),
 Prediction(uid=122662, iid=19859, r_ui=3.0, est=2.913572627136173, details={'was_impossible': False}),
 Prediction(uid=75421, iid=18319, r_ui=3.0, est=3.875324205918898, details={'was_impossible': False}),
 Prediction(uid=951, iid=1389, r_ui=2.5, est=2.654481925766257, details={'was_impossible': False}),
 Prediction(uid=270213, iid=7686, r_ui=3.0, est=2.7245582646443403, details={'was_impossible': False}),
 Prediction(uid=13234, iid=16354, r_ui=3.5, est=4.083075266467879, details={'was_impossible': False}),
 Prediction(uid=124186, iid=22698, r_ui=2.5, est=3.124718667851045, details={'was_impossible': False}),
 Prediction(uid=54848, iid=2992, r_ui=4.0, est=4.020071080202073, details={'was_impossible': False}),
 Prediction(uid=29997, iid=2929, r_ui=3.0, est=3.9423763572073027, details={'was_impossible': False}),
 Prediction(uid=123882, iid=19006, r_ui=2.0, est=2.8825489109783744, details={'was_impossible': False}),
 Prediction(uid=38668, iid=12572, r_ui=3.0, est=2.844821793002272, details={'was_impossible': False}),
 Prediction(uid=2405, iid=456, r_ui=1.0, est=3.089257278913153, details={'was_impossible': False}),
 Prediction(uid=68721, iid=6135, r_ui=3.0, est=2.811215247977917, details={'was_impossible': False}),
 Prediction(uid=74618, iid=2822, r_ui=5.0, est=4.177335621607528, details={'was_impossible': False}),
 Prediction(uid=71322, iid=3437, r_ui=3.0, est=3.701966266814997, details={'was_impossible': False}),
 Prediction(uid=28987, iid=12261, r_ui=3.0, est=3.0636300833760384, details={'was_impossible': False}),
 Prediction(uid=5235, iid=9960, r_ui=4.0, est=3.7164437787502935, details={'was_impossible': False}),
 Prediction(uid=112133, iid=9835, r_ui=3.0, est=3.555273911986348, details={'was_impossible': False}),
 Prediction(uid=268769, iid=14451, r_ui=3.5, est=3.9423730614649775, details={'was_impossible': False}),
 Prediction(uid=20020, iid=6337, r_ui=4.0, est=3.8869263308943225, details={'was_impossible': False}),
 Prediction(uid=13270, iid=14708, r_ui=4.0, est=3.831273550635566, details={'was_impossible': False}),

In [46]:
svd.predict(356,567,4)

Prediction(uid=356, iid=567, r_ui=4, est=3.729538794417126, details={'was_impossible': False})